// app/layout.tsx
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Hyunnism Portfolio",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-black text-white font-mono">
                {children}
            </body>
        </html>
    );
}
